[features]
seeds = false
skip-lint = false

[programs.localnet]
solquad = "FLvU5mPWrrxkDHfCTWV6Jz7P6e5bQvEALZ2yHTN6tLYG"

[programs.devnet]
solquad = "FLvU5mPWrrxkDHfCTWV6Jz7P6e5bQvEALZ2yHTN6tLYG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
